#!/usr/bin/env bash
# gen-catalog.sh — regenerate everything that describes the skill library, from
# the skills themselves plus mirrors.lock.json.
#
# Generates:
#   README.md                    the skills table, between <!-- skills:start/end -->
#   docs/skill-library.md        full catalog with descriptions and provenance
#   skills/mirrored/NOTICE.md    upstream + license attribution for each mirror
#   .claude-plugin/plugin.json   description field
#   .claude-plugin/marketplace.json
#
# The point is that no one hand-maintains a skill list in five places. Adding a
# skill means writing its frontmatter and running this; CI fails if the generated
# regions are stale.
#
# NOTICE.md deliberately lives beside the mirrored skills rather than inside any
# of them, because each mirrored directory has to stay byte-identical to upstream
# for sync-mirrors.sh's tree-hash comparison to work.
#
# Usage:
#   gen-catalog.sh            rewrite the generated files
#   gen-catalog.sh --check    exit 1 if any of them would change (for CI)
#
# Exit: 0 up to date / written, 1 stale (with --check), 2 bad usage.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || { echo "cannot cd to $REPO_ROOT" >&2; exit 1; }

LOCK="mirrors.lock.json"
CHECK=0

case "${1:-}" in
  --check) CHECK=1 ;;
  -h|--help) sed -n '2,24p' "$0"; exit 0 ;;
  "") ;;
  *) echo "unknown flag: $1" >&2; exit 2 ;;
esac

command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }

frontmatter() {
  awk 'NR==1 && $0 != "---" { exit 1 }
       NR==1 { next }
       /^---[[:space:]]*$/ { exit 0 }
       { print }' "$1"
}

fm_get() {
  local file="$1" key="$2" fm
  fm="$(frontmatter "$file")" || return 1
  if command -v yq >/dev/null 2>&1; then
    printf '%s\n' "$fm" | yq -r ".$key // \"\"" 2>/dev/null
  else
    printf '%s\n' "$fm" | awk -v k="$key" '
      $0 ~ "^" k ":" { sub("^" k ":[[:space:]]*", ""); val=$0; found=1; next }
      found && /^[[:space:]]+/ { sub("^[[:space:]]+", " "); val = val $0; next }
      found && /^[^[:space:]]/ { exit }
      END { if (found) print val }'
  fi
}

# Collapse to one line and escape pipes so the text is safe inside a markdown cell.
cell() { printf '%s' "$1" | tr '\n' ' ' | sed 's/|/\\|/g; s/  */ /g; s/^ //; s/ $//'; }

# First sentence, for the shorter README table.
summary() {
  printf '%s' "$1" | tr '\n' ' ' | sed 's/  */ /g' \
    | awk '{ n = match($0, /\. /); if (n > 0 && n < 400) print substr($0, 1, n); else print }' \
    | sed 's/|/\\|/g; s/^ //; s/ $//'
}

lock_field() {
  local name="$1" field="$2"
  [ -f "$LOCK" ] || return 0
  jq -r --arg n "$name" --arg f "$field" '.mirrors[$n][$f] // empty' "$LOCK" 2>/dev/null
}

list_skills() {
  find "skills/$1" -mindepth 2 -maxdepth 2 -name SKILL.md -type f 2>/dev/null | sort
}

# ------------------------------------------------------------ README section
readme_block() {
  local f name desc

  printf '### Written here\n\n'
  if [ -z "$(list_skills own)" ]; then
    printf '_None yet._\n'
  else
    printf '| Skill | What it does |\n|---|---|\n'
    while IFS= read -r f; do
      [ -n "$f" ] || continue
      name="$(fm_get "$f" name)"
      desc="$(summary "$(fm_get "$f" description)")"
      printf '| [`%s`](%s) | %s |\n' "$name" "$(dirname "$f")" "$desc"
    done < <(list_skills own)
  fi

  printf '\n### Mirrored\n\n'
  if [ -z "$(list_skills mirrored)" ]; then
    printf '_None yet — add one to [`mirrors.yaml`](mirrors.yaml)._\n'
  else
    printf 'Vendored verbatim from upstream and kept in sync automatically. Do not edit\n'
    printf 'these in place; see [docs/mirroring.md](docs/mirroring.md).\n\n'
    printf '| Skill | Upstream | License | What it does |\n|---|---|---|---|\n'
    while IFS= read -r f; do
      [ -n "$f" ] || continue
      name="$(fm_get "$f" name)"
      desc="$(summary "$(fm_get "$f" description)")"
      local repo commit license path
      repo="$(lock_field "$name" repo)"
      commit="$(lock_field "$name" commit)"
      license="$(lock_field "$name" license)"
      path="$(lock_field "$name" path)"
      if [ -n "$repo" ]; then
        printf '| [`%s`](%s) | [%s](https://github.com/%s/tree/%s/%s) `%s` | %s | %s |\n' \
          "$name" "$(dirname "$f")" "$repo" "$repo" "$commit" "$path" "${commit:0:7}" "$license" "$desc"
      else
        printf '| [`%s`](%s) | _unlocked_ | ? | %s |\n' "$name" "$(dirname "$f")" "$desc"
      fi
    done < <(list_skills mirrored)
  fi
}

# --------------------------------------------------------------- catalog page
catalog_page() {
  local f name desc

  cat <<'EOF'
<!-- Generated by scripts/gen-catalog.sh. Do not edit by hand. -->

# Skill library

Every skill this repo publishes. Install any of them with:

```bash
npx skills add sachith-gunasekara/agent-harbor -s <skill-name>
```

EOF

  printf '## Written here\n\n'
  if [ -z "$(list_skills own)" ]; then
    printf '_None yet._\n\n'
  else
    while IFS= read -r f; do
      [ -n "$f" ] || continue
      name="$(fm_get "$f" name)"
      desc="$(cell "$(fm_get "$f" description)")"
      printf '### `%s`\n\n' "$name"
      printf '%s\n\n' "$desc"
      printf -- '- Source: [`%s`](../%s)\n\n' "$(dirname "$f")" "$(dirname "$f")"
    done < <(list_skills own)
  fi

  printf '## Mirrored\n\n'
  if [ -z "$(list_skills mirrored)" ]; then
    printf '_None yet._\n'
    return
  fi
  printf 'These are copies of skills maintained elsewhere. They are re-synced\n'
  printf 'automatically and must not be edited in this repo — see\n'
  printf '[mirroring.md](mirroring.md).\n\n'
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    name="$(fm_get "$f" name)"
    desc="$(cell "$(fm_get "$f" description)")"
    local repo commit license path notes
    repo="$(lock_field "$name" repo)"
    commit="$(lock_field "$name" commit)"
    license="$(lock_field "$name" license)"
    path="$(lock_field "$name" path)"
    notes="$(lock_field "$name" notes)"
    printf '### `%s`\n\n' "$name"
    printf '%s\n\n' "$desc"
    [ -n "$notes" ] && printf 'Why it is here: %s\n\n' "$notes"
    printf -- '- Upstream: [%s/%s](https://github.com/%s/tree/%s/%s)\n' "$repo" "$path" "$repo" "$commit" "$path"
    printf -- '- Pinned commit: `%s`\n' "$commit"
    printf -- '- License: %s\n' "$license"
    printf -- '- Vendored at: [`%s`](../%s)\n\n' "$(dirname "$f")" "$(dirname "$f")"
    # synced_at is deliberately not rendered: it lives in mirrors.lock.json for
    # provenance, but putting a timestamp in a generated page would make the
    # catalog go stale on a --force run that changed nothing.
  done < <(list_skills mirrored)
}

# ----------------------------------------------------------------- NOTICE.md
notice_page() {
  cat <<'EOF'
<!-- Generated by scripts/gen-catalog.sh. Do not edit by hand. -->

# Third-party skills

Everything in this directory is copied verbatim from another repository and
remains under its original license and copyright. Nothing here is authored by
this repo's maintainer.

This file sits beside the mirrored skills rather than inside any of them so that
each mirrored directory stays byte-identical to its upstream.

EOF
  if [ -z "$(list_skills mirrored)" ]; then
    printf '_No skills are currently mirrored._\n'
    return
  fi
  local f name repo commit license path
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    name="$(fm_get "$f" name)"
    repo="$(lock_field "$name" repo)"
    commit="$(lock_field "$name" commit)"
    license="$(lock_field "$name" license)"
    path="$(lock_field "$name" path)"
    printf '## %s\n\n' "$name"
    printf -- '- Source: https://github.com/%s/tree/%s/%s\n' "$repo" "$commit" "$path"
    printf -- '- License: %s (see the LICENSE file in https://github.com/%s)\n' "$license" "$repo"
    printf -- '- Commit: %s\n\n' "$commit"
  done < <(list_skills mirrored)
}

# ------------------------------------------------------------------- helpers
plugin_description() {
  local own mirrored
  own="$(list_skills own | wc -l | tr -d ' ')"
  mirrored="$(list_skills mirrored | wc -l | tr -d ' ')"
  # Note: `paste -sd', '` cycles through both delimiter characters on BSD/macOS,
  # so join with awk instead to get a consistent ", " separator everywhere.
  local names
  names="$(while IFS= read -r f; do [ -n "$f" ] && fm_get "$f" name; done < <(list_skills own; list_skills mirrored) \
    | awk 'NR>1 { printf ", " } { printf "%s", $0 } END { print "" }')"
  printf 'Agent skills by Sachith Gunasekara — %d written here, %d mirrored from upstream repos. Includes: %s.' \
    "$own" "$mirrored" "$names"
}

# Replace the region between markers in a file.
splice() {
  local file="$1" start="$2" end="$3" body="$4" tmp
  tmp="$(mktemp)"
  awk -v start="$start" -v end="$end" -v bodyfile="$body" '
    $0 ~ start { print; while ((getline line < bodyfile) > 0) print line; skipping=1; next }
    $0 ~ end { skipping=0 }
    !skipping { print }
  ' "$file" > "$tmp"
  printf '%s' "$tmp"
}

STALE=0
report() {
  local path="$1" tmp="$2"
  # Collapse trailing newlines to exactly one. Without this the output fights the
  # end-of-file-fixer pre-commit hook: the hook trims the blank line, this script
  # writes it back, and every commit fails in a loop.
  perl -0777 -pi -e 's/\n*\z/\n/' "$tmp" 2>/dev/null || true
  if [ -f "$path" ] && cmp -s "$path" "$tmp"; then
    rm -f "$tmp"; return 0
  fi
  if [ "$CHECK" -eq 1 ]; then
    echo "STALE  $path" >&2
    STALE=1
    rm -f "$tmp"
  else
    mkdir -p "$(dirname "$path")"
    mv "$tmp" "$path"
    echo "wrote  $path"
  fi
}

# --------------------------------------------------------------------- write
BODY="$(mktemp)"
readme_block > "$BODY"
README_TMP="$(splice README.md '<!-- skills:start -->' '<!-- skills:end -->' "$BODY")"
rm -f "$BODY"
report README.md "$README_TMP"

CATALOG_TMP="$(mktemp)"
catalog_page > "$CATALOG_TMP"
report docs/skill-library.md "$CATALOG_TMP"

if [ -d skills/mirrored ]; then
  NOTICE_TMP="$(mktemp)"
  notice_page > "$NOTICE_TMP"
  report skills/mirrored/NOTICE.md "$NOTICE_TMP"
fi

DESC="$(plugin_description)"
for manifest in .claude-plugin/plugin.json .claude-plugin/marketplace.json; do
  [ -f "$manifest" ] || continue
  MTMP="$(mktemp)"
  if [ "$manifest" = ".claude-plugin/marketplace.json" ]; then
    jq --arg d "$DESC" '.metadata.description = $d | .plugins[0].description = $d' "$manifest" > "$MTMP"
  else
    jq --arg d "$DESC" '.description = $d' "$manifest" > "$MTMP"
  fi
  report "$manifest" "$MTMP"
done

if [ "$CHECK" -eq 1 ]; then
  if [ "$STALE" -ne 0 ]; then
    echo "" >&2
    echo "Generated files are out of date. Run ./scripts/gen-catalog.sh and commit the result." >&2
    exit 1
  fi
  echo "catalog is up to date"
fi
